# Path to your oh-my-zsh installation.
export ZSH="/home/lourenco/.oh-my-zsh"

# Uses hyphen insensitive completion aka - and _ are interchangeable
HYPHEN_INSENSITIVE="true"

# Enabling auto correction
ENABLE_CORRECTION="true"

# Changes the command execution time stamp in history command output
HIST_STAMPS="dd/mm/yyyy"

# Adding plugins
plugins=(git colored-man-pages zsh-syntax-highlighting)

# sourcing alias
source ~/.alias

source $ZSH/oh-my-zsh.sh

# theme configuration
ZSH_THEME="powerlevel9k/powerlevel9k"
. ~/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir ssh rbenv time vcs root_indicator status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time  custom_now_playing ram)

POWERLEVEL9K_MODE='nerdfont-complete'
ZLE_RPROMPT_INDENT=0

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"


POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\u256D \n"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\u2570 %K{013}%F{black} \Uf08a \uf6f7 have fun!%f%k%F{013}%f "

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='cyan'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='white'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='red'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='blue'

POWERLEVEL9K_DIR_BACKGROUND="032"
POWERLEVEL9K_DIR_HOME_FOREGROUND="red"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="193"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="193"

POWERLEVEL9K_CUSTOM_PID='echo -e "\uf258  $$ \uf258  `date +%d/%m/%Y`"'
POWERLEVEL9K_CUSTOM_PID_BACKGROUND="green"
POWERLEVEL9K_CUSTOM_PID_FOREGROUND="black"

POWERLEVEL9K_CUSTOM_NEWLINE="print '\n'"
POWERLEVEL9K_CUSTOM_NEWLINE_BACKGROUND="green"
POWERLEVEL9K_CUSTOM_NEWLINE_FOREGROUND="white"

POWERLEVEL9K_CUSTOM_TTY="tty"
POWERLEVEL9K_CUSTOM_TTY_BACKGROUND="blue"
POWERLEVEL9K_CUSTOM_TTY_FOREGROUND="white"

POWERLEVEL9K_CUSTOM_NOW_PLAYING='~/.nowplaying'
POWERLEVEL9K_CUSTOM_NOW_PLAYING_BACKGROUND='blue'
POWERLEVEL9K_CUSTOM_NOW_PLAYING_FOREGROUND='black'

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
